// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: agentgpu/v1/agentgpu.proto

// Package agentgpu.v1 is the versioned contract for the agent-gpu internal
// control plane: the gRPC link between the central server and each worker.
//
// The public, OpenAI-compatible HTTP API is deliberately NOT modeled here —
// this package only covers the server<->worker plane (registration,
// heartbeats, job dispatch, and results). Later epics extend this same
// package; never break it without a version bump.

package agentgpuv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Model describes an inference model a worker can serve. The fields are
// intentionally minimal for the foundational milestone; scheduling-relevant
// metadata (VRAM footprint, quantization, etc.) is added by later epics.
type Model struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Canonical model name, e.g. "llama3".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional human-readable digest/revision of the model.
	Digest        string `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{0}
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

// Error is a structured, transport-neutral error carried inside results.
// gRPC status codes cover transport failures; this models *job* failures.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Machine-readable, stable error code (e.g. "model_not_found").
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable message.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ChatMessage is one entry in an OpenAI-style chat conversation, carried on a
// Job so chat semantics round-trip from the public API through the worker to
// Ollama and back. Added by the OpenAI-API epic (#13); additive to the plain
// prompt Job carried for /v1/completions and the foundational stub.
type ChatMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Role of the author: "system", "user", "assistant", or "tool".
	Role string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// Text content of the message (may be empty for an assistant turn that only
	// carries tool_calls, or a tool result whose content is structured).
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// For a "tool" message: the id of the assistant tool call this result answers.
	ToolCallId string `protobuf:"bytes,3,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	// Optional author name (e.g. the function name for a tool message).
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// For an "assistant" message replaying prior tool calls back to the model.
	ToolCalls     []*ToolCall `protobuf:"bytes,5,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ChatMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatMessage) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

// ToolFunction is the JSON-schema function definition the client offers the
// model. parameters_json is the function's JSON-schema parameter object encoded
// as a JSON string, kept opaque on the wire so the schema passes through
// unchanged.
type ToolFunction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ParametersJson string                 `protobuf:"bytes,3,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolFunction) Reset() {
	*x = ToolFunction{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolFunction) ProtoMessage() {}

func (x *ToolFunction) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolFunction.ProtoReflect.Descriptor instead.
func (*ToolFunction) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{3}
}

func (x *ToolFunction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolFunction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolFunction) GetParametersJson() string {
	if x != nil {
		return x.ParametersJson
	}
	return ""
}

// Tool is one tool the model may call. Only function tools exist today, so type
// is "function" and function carries the definition.
type Tool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Function      *ToolFunction          `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{4}
}

func (x *Tool) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Tool) GetFunction() *ToolFunction {
	if x != nil {
		return x.Function
	}
	return nil
}

// ToolCall is a function invocation the model emitted (response side) or a
// prior assistant tool call replayed to the model (request side).
// arguments_json is the call arguments encoded as a JSON string, opaque on the
// wire.
type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	FunctionName  string                 `protobuf:"bytes,3,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	ArgumentsJson string                 `protobuf:"bytes,4,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{5}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolCall) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *ToolCall) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

// Job is a single unit of inference work dispatched from server to worker.
type Job struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned unique id for correlating dispatch with result.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the model to run the job against.
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// Free-form prompt/input for /v1/completions and the foundational stub. The
	// chat schema below (messages, tools) is the OpenAI-API epic (#13) extension;
	// a chat job leaves prompt empty and carries messages instead.
	Prompt string `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// OpenAI chat messages for /v1/chat/completions. Additive: when non-empty the
	// worker runs Ollama /api/chat with the full conversation; when empty the
	// plain prompt path is used (back-compat with the echo stub and #11).
	Messages []*ChatMessage `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	// Tools (function definitions) the model may call. Threaded to Ollama
	// /api/chat so the model can emit tool_calls.
	Tools []*Tool `protobuf:"bytes,5,rep,name=tools,proto3" json:"tools,omitempty"`
	// Model-warmth hint (#35): how long the worker should ask Ollama to keep the
	// model resident after this job, as a `keep_alive` duration in SECONDS. The
	// server sets it for session-bound turns (derived from the session's idle TTL)
	// so a model stays warm across an active conversation and unloads on its own
	// once the session goes idle; it is left 0 for session-less jobs. Semantics
	// mirror Ollama's keep_alive: 0 means "unset" — the worker omits keep_alive
	// and Ollama's default (5m) applies — a positive value keeps the model loaded
	// that many seconds (re-sent each turn, which resets Ollama's unload timer),
	// and a negative value keeps it loaded indefinitely. Additive and back-compat:
	// an unset (0) field reproduces the pre-#35 behavior exactly.
	KeepAliveSeconds int64 `protobuf:"varint,6,opt,name=keep_alive_seconds,json=keepAliveSeconds,proto3" json:"keep_alive_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{6}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Job) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Job) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *Job) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *Job) GetKeepAliveSeconds() int64 {
	if x != nil {
		return x.KeepAliveSeconds
	}
	return 0
}

// JobResult is the worker's response to a dispatched Job.
type JobResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echoes Job.id so the server can correlate.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// The produced output (stub workers echo the prompt back).
	Output string `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	// Set when the job failed; output is then empty/partial.
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Number of tokens generated/consumed by this job, reported by the worker
	// for quota accounting (#5). The echo executor reports a whitespace token
	// count; real counts arrive with the Ollama integration (#11). Zero means
	// "no tokens reported".
	Tokens uint64 `protobuf:"varint,4,opt,name=tokens,proto3" json:"tokens,omitempty"`
	// Tool calls the model emitted (OpenAI function-calling). Empty for an
	// ordinary text completion. Added by the OpenAI-API epic (#13).
	ToolCalls []*ToolCall `protobuf:"bytes,5,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	// OpenAI finish_reason for this result: "stop", "length", "tool_calls", etc.
	// Empty when the worker reports none. Added by the OpenAI-API epic (#13).
	FinishReason string `protobuf:"bytes,6,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	// Prompt-side token count (Ollama prompt_eval_count) for OpenAI usage
	// accounting; tokens above remains the total for quota. Zero if unknown.
	PromptTokens uint64 `protobuf:"varint,7,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	// Completion-side token count (Ollama eval_count). Zero if unknown.
	CompletionTokens uint64 `protobuf:"varint,8,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *JobResult) Reset() {
	*x = JobResult{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResult) ProtoMessage() {}

func (x *JobResult) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResult.ProtoReflect.Descriptor instead.
func (*JobResult) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{7}
}

func (x *JobResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *JobResult) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *JobResult) GetTokens() uint64 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

func (x *JobResult) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *JobResult) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *JobResult) GetPromptTokens() uint64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *JobResult) GetCompletionTokens() uint64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

// JobChunk is an incremental piece of a streaming job's output, sent
// worker -> server as tokens are produced. The server accumulates the deltas
// per job_id and, on the terminal chunk (done = true), resolves the pending
// job waiter with the final JobResult. This carries inference output as a true
// stream rather than a single final JobResult so the request path (#13) can
// forward it to clients as SSE.
//
// Per-token chunks carry delta (and done = false); the final chunk carries
// done = true plus the total tokens count, or done = true plus error on
// failure. delta is empty on the terminal chunk.
type JobChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echoes Job.id so the server can correlate and accumulate.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Incremental output produced since the previous chunk (empty on the
	// terminal chunk).
	Delta string `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta,omitempty"`
	// True on the final chunk for this job; no further chunks follow.
	Done bool `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	// Set on the terminal chunk when the job failed; accumulated output is then
	// discarded by the server in favor of the error.
	Error *Error `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// Total tokens generated/consumed by the job, reported on the terminal chunk
	// for quota accounting (#5). Zero means "no tokens reported".
	Tokens uint64 `protobuf:"varint,5,opt,name=tokens,proto3" json:"tokens,omitempty"`
	// Tool calls the model emitted, carried on the terminal chunk so a streaming
	// function call surfaces as delta tool_calls + finish_reason "tool_calls".
	// Added by the OpenAI-API epic (#13).
	ToolCalls []*ToolCall `protobuf:"bytes,6,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	// OpenAI finish_reason on the terminal chunk ("stop", "length",
	// "tool_calls"). Empty on non-terminal chunks. Added by the OpenAI-API epic.
	FinishReason string `protobuf:"bytes,7,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	// Prompt/completion token split on the terminal chunk for OpenAI usage.
	PromptTokens     uint64 `protobuf:"varint,8,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens uint64 `protobuf:"varint,9,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *JobChunk) Reset() {
	*x = JobChunk{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobChunk) ProtoMessage() {}

func (x *JobChunk) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobChunk.ProtoReflect.Descriptor instead.
func (*JobChunk) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{8}
}

func (x *JobChunk) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobChunk) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *JobChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *JobChunk) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *JobChunk) GetTokens() uint64 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

func (x *JobChunk) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *JobChunk) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *JobChunk) GetPromptTokens() uint64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *JobChunk) GetCompletionTokens() uint64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

// Register is the first message a worker sends on the stream. It identifies
// the worker and advertises the models it can serve.
type Register struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable, worker-chosen id (e.g. hostname or configured name).
	WorkerId string `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Models this worker can serve.
	Models        []*Model `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{9}
}

func (x *Register) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Register) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

// RegisterAck acknowledges a successful registration.
type RegisterAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned session id for this stream.
	SessionId     string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Heartbeat is sent periodically by the worker to prove liveness and report
// load and capacity signals the server uses to mark workers stale and (in a
// later epic, #9) to schedule. Real GPU detection arrives with #16; until then
// workers report stub/configured capacity.
type Heartbeat struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	WorkerId string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Number of jobs the worker is currently executing.
	ActiveJobs uint32 `protobuf:"varint,2,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	// Total VRAM on the worker's GPU(s), in bytes (0 = unknown).
	TotalVramBytes uint64 `protobuf:"varint,3,opt,name=total_vram_bytes,json=totalVramBytes,proto3" json:"total_vram_bytes,omitempty"`
	// Currently free VRAM, in bytes (0 = unknown).
	FreeVramBytes uint64 `protobuf:"varint,4,opt,name=free_vram_bytes,json=freeVramBytes,proto3" json:"free_vram_bytes,omitempty"`
	// Coarse load signal in the range 0-100 (0 = idle, 100 = saturated).
	Load uint32 `protobuf:"varint,5,opt,name=load,proto3" json:"load,omitempty"`
	// Human-readable GPU type/description (e.g. "NVIDIA RTX 4090"); empty if
	// unknown.
	GpuType string `protobuf:"bytes,6,opt,name=gpu_type,json=gpuType,proto3" json:"gpu_type,omitempty"`
	// Models the worker currently has available to serve. Lets the server's
	// fleet view reflect model availability without re-registration.
	AvailableModels []*Model `protobuf:"bytes,7,rep,name=available_models,json=availableModels,proto3" json:"available_models,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{11}
}

func (x *Heartbeat) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Heartbeat) GetActiveJobs() uint32 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

func (x *Heartbeat) GetTotalVramBytes() uint64 {
	if x != nil {
		return x.TotalVramBytes
	}
	return 0
}

func (x *Heartbeat) GetFreeVramBytes() uint64 {
	if x != nil {
		return x.FreeVramBytes
	}
	return 0
}

func (x *Heartbeat) GetLoad() uint32 {
	if x != nil {
		return x.Load
	}
	return 0
}

func (x *Heartbeat) GetGpuType() string {
	if x != nil {
		return x.GpuType
	}
	return ""
}

func (x *Heartbeat) GetAvailableModels() []*Model {
	if x != nil {
		return x.AvailableModels
	}
	return nil
}

// Deregister is sent by a worker that is shutting down gracefully. The server
// marks the worker draining: it routes no new jobs to it, lets in-flight jobs
// finish, then removes it when the stream closes.
type Deregister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deregister) Reset() {
	*x = Deregister{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deregister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deregister) ProtoMessage() {}

func (x *Deregister) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deregister.ProtoReflect.Descriptor instead.
func (*Deregister) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{12}
}

func (x *Deregister) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

// PullModel instructs a worker to fetch a model onto its local Ollama. The
// server sends it only after authorizing the requesting key for the Pull
// action (#11); the worker pulls the model and refreshes its advertised model
// list on its next heartbeat. This is an additive, fire-and-forget control
// message; pull progress/results are not streamed back today.
type PullModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the model to pull (e.g. "llama3").
	Model         string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullModel) Reset() {
	*x = PullModel{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullModel) ProtoMessage() {}

func (x *PullModel) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullModel.ProtoReflect.Descriptor instead.
func (*PullModel) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{13}
}

func (x *PullModel) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

// UnloadModel instructs a worker to evict a model from its local Ollama's
// memory now (keep_alive=0), freeing the VRAM (#35). The server sends it
// best-effort to a session's bound worker when that session is explicitly
// ended, so the conversation's model is released promptly rather than lingering
// for the remainder of its keep_alive window. Like PullModel it is additive and
// fire-and-forget: a missing/already-unloaded model is a no-op on the worker and
// no result is streamed back. The idle keep_alive timer remains the backstop
// release path, so a dropped UnloadModel still frees VRAM within the warm window.
type UnloadModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the model to unload (e.g. "llama3").
	Model         string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModel) Reset() {
	*x = UnloadModel{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModel) ProtoMessage() {}

func (x *UnloadModel) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModel.ProtoReflect.Descriptor instead.
func (*UnloadModel) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{14}
}

func (x *UnloadModel) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

// WorkerMessage is the worker -> server side of the bidi stream.
type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkerMessage_Register
	//	*WorkerMessage_Heartbeat
	//	*WorkerMessage_Result
	//	*WorkerMessage_Deregister
	//	*WorkerMessage_Chunk
	Payload       isWorkerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{15}
}

func (x *WorkerMessage) GetPayload() isWorkerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkerMessage) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *WorkerMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WorkerMessage) GetResult() *JobResult {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *WorkerMessage) GetDeregister() *Deregister {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Deregister); ok {
			return x.Deregister
		}
	}
	return nil
}

func (x *WorkerMessage) GetChunk() *JobChunk {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isWorkerMessage_Payload interface {
	isWorkerMessage_Payload()
}

type WorkerMessage_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type WorkerMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type WorkerMessage_Result struct {
	Result *JobResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

type WorkerMessage_Deregister struct {
	Deregister *Deregister `protobuf:"bytes,4,opt,name=deregister,proto3,oneof"`
}

type WorkerMessage_Chunk struct {
	Chunk *JobChunk `protobuf:"bytes,5,opt,name=chunk,proto3,oneof"`
}

func (*WorkerMessage_Register) isWorkerMessage_Payload() {}

func (*WorkerMessage_Heartbeat) isWorkerMessage_Payload() {}

func (*WorkerMessage_Result) isWorkerMessage_Payload() {}

func (*WorkerMessage_Deregister) isWorkerMessage_Payload() {}

func (*WorkerMessage_Chunk) isWorkerMessage_Payload() {}

// ServerMessage is the server -> worker side of the bidi stream.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_RegisterAck
	//	*ServerMessage_Job
	//	*ServerMessage_PullModel
	//	*ServerMessage_UnloadModel
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{16}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetRegisterAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *ServerMessage) GetJob() *Job {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Job); ok {
			return x.Job
		}
	}
	return nil
}

func (x *ServerMessage) GetPullModel() *PullModel {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PullModel); ok {
			return x.PullModel
		}
	}
	return nil
}

func (x *ServerMessage) GetUnloadModel() *UnloadModel {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_UnloadModel); ok {
			return x.UnloadModel
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_RegisterAck struct {
	RegisterAck *RegisterAck `protobuf:"bytes,1,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type ServerMessage_Job struct {
	Job *Job `protobuf:"bytes,2,opt,name=job,proto3,oneof"`
}

type ServerMessage_PullModel struct {
	PullModel *PullModel `protobuf:"bytes,3,opt,name=pull_model,json=pullModel,proto3,oneof"`
}

type ServerMessage_UnloadModel struct {
	UnloadModel *UnloadModel `protobuf:"bytes,4,opt,name=unload_model,json=unloadModel,proto3,oneof"`
}

func (*ServerMessage_RegisterAck) isServerMessage_Payload() {}

func (*ServerMessage_Job) isServerMessage_Payload() {}

func (*ServerMessage_PullModel) isServerMessage_Payload() {}

func (*ServerMessage_UnloadModel) isServerMessage_Payload() {}

var File_agentgpu_v1_agentgpu_proto protoreflect.FileDescriptor

const file_agentgpu_v1_agentgpu_proto_rawDesc = "" +
	"\n" +
	"\x1aagentgpu/v1/agentgpu.proto\x12\vagentgpu.v1\"3\n" +
	"\x05Model\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa7\x01\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12 \n" +
	"\ftool_call_id\x18\x03 \x01(\tR\n" +
	"toolCallId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x124\n" +
	"\n" +
	"tool_calls\x18\x05 \x03(\v2\x15.agentgpu.v1.ToolCallR\ttoolCalls\"m\n" +
	"\fToolFunction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12'\n" +
	"\x0fparameters_json\x18\x03 \x01(\tR\x0eparametersJson\"Q\n" +
	"\x04Tool\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x125\n" +
	"\bfunction\x18\x02 \x01(\v2\x19.agentgpu.v1.ToolFunctionR\bfunction\"z\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12#\n" +
	"\rfunction_name\x18\x03 \x01(\tR\ffunctionName\x12%\n" +
	"\x0earguments_json\x18\x04 \x01(\tR\rargumentsJson\"\xd0\x01\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x124\n" +
	"\bmessages\x18\x04 \x03(\v2\x18.agentgpu.v1.ChatMessageR\bmessages\x12'\n" +
	"\x05tools\x18\x05 \x03(\v2\x11.agentgpu.v1.ToolR\x05tools\x12,\n" +
	"\x12keep_alive_seconds\x18\x06 \x01(\x03R\x10keepAliveSeconds\"\xa9\x02\n" +
	"\tJobResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12(\n" +
	"\x05error\x18\x03 \x01(\v2\x12.agentgpu.v1.ErrorR\x05error\x12\x16\n" +
	"\x06tokens\x18\x04 \x01(\x04R\x06tokens\x124\n" +
	"\n" +
	"tool_calls\x18\x05 \x03(\v2\x15.agentgpu.v1.ToolCallR\ttoolCalls\x12#\n" +
	"\rfinish_reason\x18\x06 \x01(\tR\ffinishReason\x12#\n" +
	"\rprompt_tokens\x18\a \x01(\x04R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\b \x01(\x04R\x10completionTokens\"\xba\x02\n" +
	"\bJobChunk\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\tR\x05delta\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\x12(\n" +
	"\x05error\x18\x04 \x01(\v2\x12.agentgpu.v1.ErrorR\x05error\x12\x16\n" +
	"\x06tokens\x18\x05 \x01(\x04R\x06tokens\x124\n" +
	"\n" +
	"tool_calls\x18\x06 \x03(\v2\x15.agentgpu.v1.ToolCallR\ttoolCalls\x12#\n" +
	"\rfinish_reason\x18\a \x01(\tR\ffinishReason\x12#\n" +
	"\rprompt_tokens\x18\b \x01(\x04R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\t \x01(\x04R\x10completionTokens\"S\n" +
	"\bRegister\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12*\n" +
	"\x06models\x18\x02 \x03(\v2\x12.agentgpu.v1.ModelR\x06models\",\n" +
	"\vRegisterAck\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x89\x02\n" +
	"\tHeartbeat\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1f\n" +
	"\vactive_jobs\x18\x02 \x01(\rR\n" +
	"activeJobs\x12(\n" +
	"\x10total_vram_bytes\x18\x03 \x01(\x04R\x0etotalVramBytes\x12&\n" +
	"\x0ffree_vram_bytes\x18\x04 \x01(\x04R\rfreeVramBytes\x12\x12\n" +
	"\x04load\x18\x05 \x01(\rR\x04load\x12\x19\n" +
	"\bgpu_type\x18\x06 \x01(\tR\agpuType\x12=\n" +
	"\x10available_models\x18\a \x03(\v2\x12.agentgpu.v1.ModelR\x0favailableModels\")\n" +
	"\n" +
	"Deregister\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"!\n" +
	"\tPullModel\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\"#\n" +
	"\vUnloadModel\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\"\xa3\x02\n" +
	"\rWorkerMessage\x123\n" +
	"\bregister\x18\x01 \x01(\v2\x15.agentgpu.v1.RegisterH\x00R\bregister\x126\n" +
	"\theartbeat\x18\x02 \x01(\v2\x16.agentgpu.v1.HeartbeatH\x00R\theartbeat\x120\n" +
	"\x06result\x18\x03 \x01(\v2\x16.agentgpu.v1.JobResultH\x00R\x06result\x129\n" +
	"\n" +
	"deregister\x18\x04 \x01(\v2\x17.agentgpu.v1.DeregisterH\x00R\n" +
	"deregister\x12-\n" +
	"\x05chunk\x18\x05 \x01(\v2\x15.agentgpu.v1.JobChunkH\x00R\x05chunkB\t\n" +
	"\apayload\"\xf7\x01\n" +
	"\rServerMessage\x12=\n" +
	"\fregister_ack\x18\x01 \x01(\v2\x18.agentgpu.v1.RegisterAckH\x00R\vregisterAck\x12$\n" +
	"\x03job\x18\x02 \x01(\v2\x10.agentgpu.v1.JobH\x00R\x03job\x127\n" +
	"\n" +
	"pull_model\x18\x03 \x01(\v2\x16.agentgpu.v1.PullModelH\x00R\tpullModel\x12=\n" +
	"\funload_model\x18\x04 \x01(\v2\x18.agentgpu.v1.UnloadModelH\x00R\vunloadModelB\t\n" +
	"\apayload2U\n" +
	"\fControlPlane\x12E\n" +
	"\aConnect\x12\x1a.agentgpu.v1.WorkerMessage\x1a\x1a.agentgpu.v1.ServerMessage(\x010\x01B<Z:github.com/jaypetez/agent-gpu/proto/agentgpu/v1;agentgpuv1b\x06proto3"

var (
	file_agentgpu_v1_agentgpu_proto_rawDescOnce sync.Once
	file_agentgpu_v1_agentgpu_proto_rawDescData []byte
)

func file_agentgpu_v1_agentgpu_proto_rawDescGZIP() []byte {
	file_agentgpu_v1_agentgpu_proto_rawDescOnce.Do(func() {
		file_agentgpu_v1_agentgpu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agentgpu_v1_agentgpu_proto_rawDesc), len(file_agentgpu_v1_agentgpu_proto_rawDesc)))
	})
	return file_agentgpu_v1_agentgpu_proto_rawDescData
}

var file_agentgpu_v1_agentgpu_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_agentgpu_v1_agentgpu_proto_goTypes = []any{
	(*Model)(nil),         // 0: agentgpu.v1.Model
	(*Error)(nil),         // 1: agentgpu.v1.Error
	(*ChatMessage)(nil),   // 2: agentgpu.v1.ChatMessage
	(*ToolFunction)(nil),  // 3: agentgpu.v1.ToolFunction
	(*Tool)(nil),          // 4: agentgpu.v1.Tool
	(*ToolCall)(nil),      // 5: agentgpu.v1.ToolCall
	(*Job)(nil),           // 6: agentgpu.v1.Job
	(*JobResult)(nil),     // 7: agentgpu.v1.JobResult
	(*JobChunk)(nil),      // 8: agentgpu.v1.JobChunk
	(*Register)(nil),      // 9: agentgpu.v1.Register
	(*RegisterAck)(nil),   // 10: agentgpu.v1.RegisterAck
	(*Heartbeat)(nil),     // 11: agentgpu.v1.Heartbeat
	(*Deregister)(nil),    // 12: agentgpu.v1.Deregister
	(*PullModel)(nil),     // 13: agentgpu.v1.PullModel
	(*UnloadModel)(nil),   // 14: agentgpu.v1.UnloadModel
	(*WorkerMessage)(nil), // 15: agentgpu.v1.WorkerMessage
	(*ServerMessage)(nil), // 16: agentgpu.v1.ServerMessage
}
var file_agentgpu_v1_agentgpu_proto_depIdxs = []int32{
	5,  // 0: agentgpu.v1.ChatMessage.tool_calls:type_name -> agentgpu.v1.ToolCall
	3,  // 1: agentgpu.v1.Tool.function:type_name -> agentgpu.v1.ToolFunction
	2,  // 2: agentgpu.v1.Job.messages:type_name -> agentgpu.v1.ChatMessage
	4,  // 3: agentgpu.v1.Job.tools:type_name -> agentgpu.v1.Tool
	1,  // 4: agentgpu.v1.JobResult.error:type_name -> agentgpu.v1.Error
	5,  // 5: agentgpu.v1.JobResult.tool_calls:type_name -> agentgpu.v1.ToolCall
	1,  // 6: agentgpu.v1.JobChunk.error:type_name -> agentgpu.v1.Error
	5,  // 7: agentgpu.v1.JobChunk.tool_calls:type_name -> agentgpu.v1.ToolCall
	0,  // 8: agentgpu.v1.Register.models:type_name -> agentgpu.v1.Model
	0,  // 9: agentgpu.v1.Heartbeat.available_models:type_name -> agentgpu.v1.Model
	9,  // 10: agentgpu.v1.WorkerMessage.register:type_name -> agentgpu.v1.Register
	11, // 11: agentgpu.v1.WorkerMessage.heartbeat:type_name -> agentgpu.v1.Heartbeat
	7,  // 12: agentgpu.v1.WorkerMessage.result:type_name -> agentgpu.v1.JobResult
	12, // 13: agentgpu.v1.WorkerMessage.deregister:type_name -> agentgpu.v1.Deregister
	8,  // 14: agentgpu.v1.WorkerMessage.chunk:type_name -> agentgpu.v1.JobChunk
	10, // 15: agentgpu.v1.ServerMessage.register_ack:type_name -> agentgpu.v1.RegisterAck
	6,  // 16: agentgpu.v1.ServerMessage.job:type_name -> agentgpu.v1.Job
	13, // 17: agentgpu.v1.ServerMessage.pull_model:type_name -> agentgpu.v1.PullModel
	14, // 18: agentgpu.v1.ServerMessage.unload_model:type_name -> agentgpu.v1.UnloadModel
	15, // 19: agentgpu.v1.ControlPlane.Connect:input_type -> agentgpu.v1.WorkerMessage
	16, // 20: agentgpu.v1.ControlPlane.Connect:output_type -> agentgpu.v1.ServerMessage
	20, // [20:21] is the sub-list for method output_type
	19, // [19:20] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_agentgpu_v1_agentgpu_proto_init() }
func file_agentgpu_v1_agentgpu_proto_init() {
	if File_agentgpu_v1_agentgpu_proto != nil {
		return
	}
	file_agentgpu_v1_agentgpu_proto_msgTypes[15].OneofWrappers = []any{
		(*WorkerMessage_Register)(nil),
		(*WorkerMessage_Heartbeat)(nil),
		(*WorkerMessage_Result)(nil),
		(*WorkerMessage_Deregister)(nil),
		(*WorkerMessage_Chunk)(nil),
	}
	file_agentgpu_v1_agentgpu_proto_msgTypes[16].OneofWrappers = []any{
		(*ServerMessage_RegisterAck)(nil),
		(*ServerMessage_Job)(nil),
		(*ServerMessage_PullModel)(nil),
		(*ServerMessage_UnloadModel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agentgpu_v1_agentgpu_proto_rawDesc), len(file_agentgpu_v1_agentgpu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agentgpu_v1_agentgpu_proto_goTypes,
		DependencyIndexes: file_agentgpu_v1_agentgpu_proto_depIdxs,
		MessageInfos:      file_agentgpu_v1_agentgpu_proto_msgTypes,
	}.Build()
	File_agentgpu_v1_agentgpu_proto = out.File
	file_agentgpu_v1_agentgpu_proto_goTypes = nil
	file_agentgpu_v1_agentgpu_proto_depIdxs = nil
}
