// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: agentgpu/v1/agentgpu.proto

// Package agentgpu.v1 is the versioned contract for the agent-gpu internal
// control plane: the gRPC link between the central server and each worker.
//
// The public, OpenAI-compatible HTTP API is deliberately NOT modeled here —
// this package only covers the server<->worker plane (registration,
// heartbeats, job dispatch, and results). Later epics extend this same
// package; never break it without a version bump.

package agentgpuv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Model describes an inference model a worker can serve. The fields are
// intentionally minimal for the foundational milestone; scheduling-relevant
// metadata (VRAM footprint, quantization, etc.) is added by later epics.
type Model struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Canonical model name, e.g. "llama3".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional human-readable digest/revision of the model.
	Digest        string `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{0}
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

// Error is a structured, transport-neutral error carried inside results.
// gRPC status codes cover transport failures; this models *job* failures.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Machine-readable, stable error code (e.g. "model_not_found").
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable message.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Job is a single unit of inference work dispatched from server to worker.
type Job struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned unique id for correlating dispatch with result.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the model to run the job against.
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// Free-form prompt/input. The real schema (chat messages, params) is built
	// by the OpenAI-API epic; for the foundational stub this is a plain prompt.
	Prompt        string `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{2}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Job) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

// JobResult is the worker's response to a dispatched Job.
type JobResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echoes Job.id so the server can correlate.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// The produced output (stub workers echo the prompt back).
	Output string `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	// Set when the job failed; output is then empty/partial.
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Number of tokens generated/consumed by this job, reported by the worker
	// for quota accounting (#5). The echo executor reports a whitespace token
	// count; real counts arrive with the Ollama integration (#11). Zero means
	// "no tokens reported".
	Tokens        uint64 `protobuf:"varint,4,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResult) Reset() {
	*x = JobResult{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResult) ProtoMessage() {}

func (x *JobResult) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResult.ProtoReflect.Descriptor instead.
func (*JobResult) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{3}
}

func (x *JobResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *JobResult) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *JobResult) GetTokens() uint64 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

// Register is the first message a worker sends on the stream. It identifies
// the worker and advertises the models it can serve.
type Register struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable, worker-chosen id (e.g. hostname or configured name).
	WorkerId string `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Models this worker can serve.
	Models        []*Model `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{4}
}

func (x *Register) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Register) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

// RegisterAck acknowledges a successful registration.
type RegisterAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned session id for this stream.
	SessionId     string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Heartbeat is sent periodically by the worker to prove liveness and report
// lightweight load signals. Capacity-aware scheduling fields are added later.
type Heartbeat struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	WorkerId string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Number of jobs the worker is currently executing.
	ActiveJobs    uint32 `protobuf:"varint,2,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{6}
}

func (x *Heartbeat) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Heartbeat) GetActiveJobs() uint32 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

// WorkerMessage is the worker -> server side of the bidi stream.
type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkerMessage_Register
	//	*WorkerMessage_Heartbeat
	//	*WorkerMessage_Result
	Payload       isWorkerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{7}
}

func (x *WorkerMessage) GetPayload() isWorkerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkerMessage) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *WorkerMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WorkerMessage) GetResult() *JobResult {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isWorkerMessage_Payload interface {
	isWorkerMessage_Payload()
}

type WorkerMessage_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type WorkerMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type WorkerMessage_Result struct {
	Result *JobResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

func (*WorkerMessage_Register) isWorkerMessage_Payload() {}

func (*WorkerMessage_Heartbeat) isWorkerMessage_Payload() {}

func (*WorkerMessage_Result) isWorkerMessage_Payload() {}

// ServerMessage is the server -> worker side of the bidi stream.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_RegisterAck
	//	*ServerMessage_Job
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agentgpu_v1_agentgpu_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_agentgpu_v1_agentgpu_proto_rawDescGZIP(), []int{8}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetRegisterAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *ServerMessage) GetJob() *Job {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Job); ok {
			return x.Job
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_RegisterAck struct {
	RegisterAck *RegisterAck `protobuf:"bytes,1,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type ServerMessage_Job struct {
	Job *Job `protobuf:"bytes,2,opt,name=job,proto3,oneof"`
}

func (*ServerMessage_RegisterAck) isServerMessage_Payload() {}

func (*ServerMessage_Job) isServerMessage_Payload() {}

var File_agentgpu_v1_agentgpu_proto protoreflect.FileDescriptor

const file_agentgpu_v1_agentgpu_proto_rawDesc = "" +
	"\n" +
	"\x1aagentgpu/v1/agentgpu.proto\x12\vagentgpu.v1\"3\n" +
	"\x05Model\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"C\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\"|\n" +
	"\tJobResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12(\n" +
	"\x05error\x18\x03 \x01(\v2\x12.agentgpu.v1.ErrorR\x05error\x12\x16\n" +
	"\x06tokens\x18\x04 \x01(\x04R\x06tokens\"S\n" +
	"\bRegister\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12*\n" +
	"\x06models\x18\x02 \x03(\v2\x12.agentgpu.v1.ModelR\x06models\",\n" +
	"\vRegisterAck\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"I\n" +
	"\tHeartbeat\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1f\n" +
	"\vactive_jobs\x18\x02 \x01(\rR\n" +
	"activeJobs\"\xb9\x01\n" +
	"\rWorkerMessage\x123\n" +
	"\bregister\x18\x01 \x01(\v2\x15.agentgpu.v1.RegisterH\x00R\bregister\x126\n" +
	"\theartbeat\x18\x02 \x01(\v2\x16.agentgpu.v1.HeartbeatH\x00R\theartbeat\x120\n" +
	"\x06result\x18\x03 \x01(\v2\x16.agentgpu.v1.JobResultH\x00R\x06resultB\t\n" +
	"\apayload\"\x7f\n" +
	"\rServerMessage\x12=\n" +
	"\fregister_ack\x18\x01 \x01(\v2\x18.agentgpu.v1.RegisterAckH\x00R\vregisterAck\x12$\n" +
	"\x03job\x18\x02 \x01(\v2\x10.agentgpu.v1.JobH\x00R\x03jobB\t\n" +
	"\apayload2U\n" +
	"\fControlPlane\x12E\n" +
	"\aConnect\x12\x1a.agentgpu.v1.WorkerMessage\x1a\x1a.agentgpu.v1.ServerMessage(\x010\x01B<Z:github.com/jaypetez/agent-gpu/proto/agentgpu/v1;agentgpuv1b\x06proto3"

var (
	file_agentgpu_v1_agentgpu_proto_rawDescOnce sync.Once
	file_agentgpu_v1_agentgpu_proto_rawDescData []byte
)

func file_agentgpu_v1_agentgpu_proto_rawDescGZIP() []byte {
	file_agentgpu_v1_agentgpu_proto_rawDescOnce.Do(func() {
		file_agentgpu_v1_agentgpu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agentgpu_v1_agentgpu_proto_rawDesc), len(file_agentgpu_v1_agentgpu_proto_rawDesc)))
	})
	return file_agentgpu_v1_agentgpu_proto_rawDescData
}

var file_agentgpu_v1_agentgpu_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_agentgpu_v1_agentgpu_proto_goTypes = []any{
	(*Model)(nil),         // 0: agentgpu.v1.Model
	(*Error)(nil),         // 1: agentgpu.v1.Error
	(*Job)(nil),           // 2: agentgpu.v1.Job
	(*JobResult)(nil),     // 3: agentgpu.v1.JobResult
	(*Register)(nil),      // 4: agentgpu.v1.Register
	(*RegisterAck)(nil),   // 5: agentgpu.v1.RegisterAck
	(*Heartbeat)(nil),     // 6: agentgpu.v1.Heartbeat
	(*WorkerMessage)(nil), // 7: agentgpu.v1.WorkerMessage
	(*ServerMessage)(nil), // 8: agentgpu.v1.ServerMessage
}
var file_agentgpu_v1_agentgpu_proto_depIdxs = []int32{
	1, // 0: agentgpu.v1.JobResult.error:type_name -> agentgpu.v1.Error
	0, // 1: agentgpu.v1.Register.models:type_name -> agentgpu.v1.Model
	4, // 2: agentgpu.v1.WorkerMessage.register:type_name -> agentgpu.v1.Register
	6, // 3: agentgpu.v1.WorkerMessage.heartbeat:type_name -> agentgpu.v1.Heartbeat
	3, // 4: agentgpu.v1.WorkerMessage.result:type_name -> agentgpu.v1.JobResult
	5, // 5: agentgpu.v1.ServerMessage.register_ack:type_name -> agentgpu.v1.RegisterAck
	2, // 6: agentgpu.v1.ServerMessage.job:type_name -> agentgpu.v1.Job
	7, // 7: agentgpu.v1.ControlPlane.Connect:input_type -> agentgpu.v1.WorkerMessage
	8, // 8: agentgpu.v1.ControlPlane.Connect:output_type -> agentgpu.v1.ServerMessage
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_agentgpu_v1_agentgpu_proto_init() }
func file_agentgpu_v1_agentgpu_proto_init() {
	if File_agentgpu_v1_agentgpu_proto != nil {
		return
	}
	file_agentgpu_v1_agentgpu_proto_msgTypes[7].OneofWrappers = []any{
		(*WorkerMessage_Register)(nil),
		(*WorkerMessage_Heartbeat)(nil),
		(*WorkerMessage_Result)(nil),
	}
	file_agentgpu_v1_agentgpu_proto_msgTypes[8].OneofWrappers = []any{
		(*ServerMessage_RegisterAck)(nil),
		(*ServerMessage_Job)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agentgpu_v1_agentgpu_proto_rawDesc), len(file_agentgpu_v1_agentgpu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agentgpu_v1_agentgpu_proto_goTypes,
		DependencyIndexes: file_agentgpu_v1_agentgpu_proto_depIdxs,
		MessageInfos:      file_agentgpu_v1_agentgpu_proto_msgTypes,
	}.Build()
	File_agentgpu_v1_agentgpu_proto = out.File
	file_agentgpu_v1_agentgpu_proto_goTypes = nil
	file_agentgpu_v1_agentgpu_proto_depIdxs = nil
}
